export const MAX_LENGHT_NAME = 60
export const MIN_LENGHT_NAME = 2
export const MIN_LENGHT_PASSWORD = 8

export const MIN_LENGHT_CATEGORY_NAME = 3
export const MAX_LENGHT_CATEGORY_NAME = 50
export const MIN_LENGHT_SUBCATEGORY_NAME = 3
export const MAX_LENGHT_SUBCATEGORY_NAME = 50
export const MIN_LENGHT_TOPIC_NAME = 1
export const MAX_LENGHT_TOPIC_NAME = 50
export const MAX_LENGHT_DESCRIPTION = 300
export const MIN_LENGHT_DESCRIPTION = 10
